import React from 'react';

const ResultsDisplay = ({ results }) => {
    if (!results) return null;

    return (
        <div className="bg-white dark:bg-gray-800 p-6 rounded-xl shadow-lg border border-gray-100 dark:border-gray-700 space-y-6 animate-fade-in-up">
            <h2 className="text-2xl font-bold text-gray-800 dark:text-white border-b pb-2 dark:border-gray-700">Analysis Results</h2>

            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {/* Status Badge */}
                <div className="p-4 rounded-lg bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 flex flex-col items-center justify-center">
                    <span className="text-sm text-gray-500 dark:text-gray-400 uppercase tracking-wider font-semibold mb-1">Generated By</span>
                    <span className={`text-lg font-bold px-3 py-1 rounded-full ${results.is_ai_generated
                            ? 'bg-purple-100 text-purple-700 dark:bg-purple-900 dark:text-purple-300'
                            : 'bg-green-100 text-green-700 dark:bg-green-900 dark:text-green-300'
                        }`}>
                        {results.is_ai_generated ? 'AI Model' : 'Human'}
                    </span>
                </div>

                {/* Authenticity Score */}
                <div className="p-4 rounded-lg bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 flex flex-col items-center justify-center">
                    <span className="text-sm text-gray-500 dark:text-gray-400 uppercase tracking-wider font-semibold mb-1">Authenticity</span>
                    <div className="text-3xl font-bold text-indigo-600 dark:text-indigo-400">
                        {(results.authenticity_score * 100).toFixed(0)}%
                    </div>
                </div>

                {/* Virality Score */}
                <div className="p-4 rounded-lg bg-gray-50 dark:bg-gray-900 border border-gray-200 dark:border-gray-700 flex flex-col items-center justify-center">
                    <span className="text-sm text-gray-500 dark:text-gray-400 uppercase tracking-wider font-semibold mb-1">Virality Potential</span>
                    <div className="text-3xl font-bold text-pink-600 dark:text-pink-400">
                        {results.virality_score.toFixed(0)}/100
                    </div>
                </div>
            </div>

            {/* Target Audience */}
            <div>
                <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-200 mb-2">Target Audience</h3>
                <div className="flex flex-wrap gap-2">
                    {results.target_audience.map((audience, index) => (
                        <span key={index} className="px-3 py-1 bg-blue-100 text-blue-700 dark:bg-blue-900 dark:text-blue-300 rounded-full text-sm font-medium">
                            {audience}
                        </span>
                    ))}
                </div>
            </div>

            {/* Reasoning */}
            <div>
                <h3 className="text-lg font-semibold text-gray-700 dark:text-gray-200 mb-2">Reasoning</h3>
                <div className="p-4 bg-gray-50 dark:bg-gray-700/50 rounded-lg text-gray-600 dark:text-gray-300 leading-relaxed">
                    {results.reasoning}
                </div>
            </div>
        </div>
    );
};

export default ResultsDisplay;
